### ISSUE TITLE
Can't run sampl app

### ISSUE THREAD

**Issue by agzamovr** [pushtorefresh/storio#664]
I got following error while running sample app on emulator
```
Service com.google.android.gms.chimera.GmsIntentOperationService has leaked IntentReceiver fvn@98b3276 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Service com.google.android.gms.chimera.GmsIntentOperationService has leaked IntentReceiver fvn@98b3276 that was originally registered here. Are you missing a call to unregisterReceiver()?
       at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:918)
       at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:719)
       at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1172)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1152)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1146)
       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:554)
       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:554)
       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:554)
       at com.google.android.gms.auth.setup.devicesignals.LockScreenChimeraReceiver.a(SourceFile:52)
       at fvo.b(SourceFile:2036)
       at com.google.android.gms.auth.account.AuthInitIntentOperation.a(SourceFile:62)
       at hwg.onHandleIntent(SourceFile:60)
       at com.google.android.chimera.IntentOperation.onHandleIntent(SourceFile:82)
```
How this can be fixed?

**Comment by nikitin-da** [comment]
Hi, @agzamovr! There are no receivers in sample app. Could you provide me with an actual StorIO sample crash log?

**Comment by agzamovr** [comment]
Hmm, interesting, there is stack trace for new error which i've not seen before but now it directly related to sample app:
```
FATAL EXCEPTION: main
Process: com.pushtorefresh.storio.sample, PID: 2834
java.lang.RuntimeException: Unable to get provider com.pushtorefresh.storio.sample.provider.SampleContentProvider: java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication cannot be cast to com.pushtorefresh.storio.sample.SampleApp
    at android.app.ActivityThread.installProvider(ActivityThread.java:5156)
    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
    at android.app.ActivityThread.-wrap1(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication cannot be cast to com.pushtorefresh.storio.sample.SampleApp
    at com.pushtorefresh.storio.sample.SampleApp.get(SampleApp.java:27)
    at com.pushtorefresh.storio.sample.provider.SampleContentProvider.onCreate(SampleContentProvider.java:39)
    at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
    at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
    at android.app.ActivityThread.installProvider(ActivityThread.java:5153)
    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748) 
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688) 
    at android.app.ActivityThread.-wrap1(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5417) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```
The only change which i've made to project is commented android-sdk-manager dependency and plugin in build files because it does not work with latest gradle version (2.+)

**Comment by nikitin-da** [comment]
Can you [disable instant run](http://stackoverflow.com/a/36576011), please? =)

**Comment by agzamovr** [comment]
Yes, this helped. Ii hope you will fix issue with instant run in future. 
Thank you!

**Comment by artem-zinnatullin** [comment]
That's tools problem, not library :)
