### ISSUE TITLE
Migrate to AGP 3.0

### ISSUE THREAD

**Issue by geralt-encore** [pushtorefresh/storio#851]
I already tried couple of times and failed miserably 😔

**Comment by Sar777** [comment]
hi guys, i have DEX build an error with gradle 3.0

stacktrace

```
Caused by: com.android.dex.DexException: Multiple dex files define Lcom/pushtorefresh/storio2/R;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
        at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
```
